**Very small** changes to the smg to make the recoil less intense when you are strafing.
momentum-mod/game pull request #1022
Opened 2020-10-14 01:19 UTC by CoopJax

A tiny edit to smg recoil when you're moving. It might not be needed and that's fine. Thanks alot for reviewing this in advance :)

### Checklist
- [x ] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [ ] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [ ] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [ x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
[Recoil Demo](https://cdn.discordapp.com/attachments/765655141525225483/765738843423899668/2020-10-13_19-52-03.mp4) (Note that I am shooting the entire time)
- [ ] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x ] My commits are relatively small and scoped to the best of my ability
- [ x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x ] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

2020-10-14 13:14 UTC, CoopJax commented
I didn't want this to be opened quite yet... I wanted to edit some files so that the build wouldn't break.

2020-10-14 14:25 UTC, braem commented on mp/src/game/shared/momentum/weapon/weapon_mom_smg.cpp
> +        pPlayer->KickBack(1.0, 0.55, 0.40, 0.04, 6.0, 4.0, 5);
More kickback when we're on the ground? Confused by this change.

2020-10-14 14:32 UTC, CoopJax commented
Yeah, I was trying to rename it to mom_weapon_machinegun and it broke everything. I'll try that.

2020-10-14 14:37 UTC, braem commented
> 
> 
> Yeah, I was trying to rename it to mom_weapon_machinegun and it broke everything. I'll try that.

Also please include a commit summary instead of leaving it blank to avoid getting commits like "Update mom_weapon_smg".

2020-10-14 15:12 UTC, CoopJax commented
There still seems to be an error that I can't figure out.

2020-10-14 15:49 UTC, CoopJax commented
But I think I got mostly everything

2020-10-14 15:56 UTC, CoopJax commented
> Remember to change the `#include` at the top of the files as well, it still points to the old file.
On what files?

2020-10-14 17:30 UTC, Gocnak commented
Try to compile the game after every change and before you commit. It helps a lot with finding issues.

2020-10-14 17:36 UTC, CoopJax commented
Yeah, I found the error. It's really cryptic and confusing though. Something to do with the build script, not my actual code.

2020-10-14 17:39 UTC, Gocnak commented
Well there still is an issue with your code.

When you rename something, you have to make sure there's not leftovers in various files. Try searching for "mom_weapon_smg". Visual studio should also be highlighting things wrong with red.

2020-10-14 18:12 UTC, CoopJax commented
Well I tried to find anything with weapon_mom_smg in it and change it. Build is still giving me an error. <img src="https://i.imgur.com/ulURQzQ.png" alt="error" data-canonical-src="https://i.imgur.com/ulURQzQ.png" style="max-width:100%;">

2020-10-14 18:28 UTC, Gocnak commented
Ah. Any time you edit any vpc file, or change branch on git, you'll want to rerun `creategameprojects.bat`. Not as admin, just normally. This will generate an updated momentum.sln.

2020-10-14 18:33 UTC, CoopJax commented
Ok, I did it. It debugged and ran successfully!

2020-10-14 18:58 UTC, CoopJax commented
Everything is working and i'm done here.

2020-10-14 19:08 UTC, Gocnak requested changes

2020-10-14 19:08 UTC, Gocnak commented on mp/src/game/client/client_momentum.vpc
>                  $File "$SRCDIR\game\shared\momentum\weapon\weapon_mom_smg.h"
Rename the header to match.

2020-10-14 19:08 UTC, CoopJax commented on mp/src/game/client/client_momentum.vpc
>                  $File "$SRCDIR\game\shared\momentum\weapon\weapon_mom_smg.h"
Oh, forgot about that.

2020-10-14 19:49 UTC, CoopJax commented
Header file errors are fixed and renamed.

2020-10-14 23:59 UTC, CoopJax commented
Is everything good now? Anything extra I need to do?

2020-10-15 00:02 UTC, Gocnak approved these changes

2020-10-15 00:04 UTC, merged