Add catapult
momentum-mod/game pull request #926
Opened 2020-09-07 20:49 UTC by notbad69

Closes  #865

Adds the trigger_momentum_catapult to mimic the trigger_catapult present in tf2.

This is not 1:1 as per the tf2 fgd: vphys and the random angular impulse are not currently supported, exposed options for the think interval 

### Checklist
- [ ] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [ x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [ x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [ x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [ ] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [ x] My commits are relatively small and scoped to the best of my ability
- [x ] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [ ] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

2020-09-10 08:19 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +    float flSpeed4 = m_flPlayerSpeed * m_flPlayerSpeed * m_flPlayerSpeed * m_flPlayerSpeed;
"2" and "4" are not as clear as
```suggestion
    float flSpeedSquared = m_flPlayerSpeed * m_flPlayerSpeed;
    float flSpeedQuad = m_flPlayerSpeed * m_flPlayerSpeed * m_flPlayerSpeed * m_flPlayerSpeed;
```

2020-09-10 08:21 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +    Vector vecHighAngVelocity = m_flPlayerSpeed * (fGroundDir * cosf(flHighAng) + Vector(0, 0, 1) * sinf(flHighAng));
```suggestion
    Vector vecLowAngVelocity = m_flPlayerSpeed * (fGroundDir * cosf(flLowAng) + Vector(0, 0, sinf(flLowAng)));
    Vector vecHighAngVelocity = m_flPlayerSpeed * (fGroundDir * cosf(flHighAng) + Vector(0, 0, sinf(flHighAng)));
```

2020-09-10 08:23 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +    }
```suggestion
    Vector vecLaunchVelocity = vec3_origin;
    if (m_iUseExactVelocity)
    {
        vecLaunchVelocity = CalculateLaunchVelocityExact(pOther);
    }
    else
    {
        vecLaunchVelocity = CalculateLaunchVelocity(pOther);
    }
    pOther->SetAbsVelocity(vecLaunchVelocity);
```

2020-09-10 08:25 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +    if (flAbsX == 0.0f)
```suggestion
    if (CloseEnough(flAbsX, 0.0f))
```

2020-09-10 08:27 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +        Vector vecPlayerOrigin = this->GetAbsOrigin();
`this->` is redundant.
```suggestion
        Vector vecPlayerOrigin = GetAbsOrigin();
```

2020-09-10 08:27 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +
Spacing, use one line of empty space instead of multiple

2020-09-10 08:27 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.h
> +// CTriggerMomentumCatapult
You can remove this comment, it's not very useful.

2020-09-10 08:28 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.h
> +    };
It's good to name your enums:
```suggestion
    enum ExactVelocityChoice_t
    {
        BEST = 0,
        SOLUTION_ONE,
        SOLUTION_TWO,
    };
```

2020-09-10 08:34 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +            }
These two branches of code use very similar logic. Consider pulling the common code out:
```suggestion
        float flPlayerEntryAng;
        if (m_bUseLaunchTarget)
        {
            Vector vecAbsDifference = m_hLaunchTarget->GetAbsOrigin() - pOther->GetAbsOrigin();
            flPlayerEntryAng = DotProduct(vecAbsDifference.Normalized(), vecPlayerVelocity.Normalized());
        }
        else
        {
             Vector vecLaunchDir = vec3_origin;
             AngleVectors(m_vLaunchDirection, &vecLaunchDir);
             flPlayerEntryAng = DotProduct(vecLaunchDir.Normalized(), vecPlayerVelocity.Normalized());
         }

         // VDC uses brackets so inclusive??
         if (flPlayerEntryAng >= m_flEntryAngleTolerance)
         {
             if (m_bOnlyCheckVelocity)
             {
                 m_OnCatapulted.FireOutput(pOther, this);
                 return;
             }
             
             bLaunch = true;
         }
```

2020-09-10 08:37 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.h
> +    void Spawn() OVERRIDE;
Use `override` instead of `OVERRIDE`
```suggestion
    void Spawn() override;
```

2020-09-10 08:38 UTC, Gocnak commented on mp/src/game/server/momentum/mom_triggers.cpp
> +    }
Early return to save on pointless indentation here:
```suggestion
    if (!bLaunch)
        return;
    
    if (m_bUseLaunchTarget)
    {
        LaunchAtTarget(pOther);
    }
    else
    {
        LaunchAtDirection(pOther);
    }
```

2020-09-12 16:58 UTC, notbad69 commented on mp/game/momentum/momentum.fgd
> -    EveryTick(integer) : "Every tick" : 0 : "If you want the trigger to update and fire every tick, set this to 1."
This isn't part of the original entity, and it seemed redundant since there is control over the interval already

2020-09-13 01:45 UTC, Gocnak requested changes

2020-09-13 01:45 UTC, Gocnak commented on mp/game/momentum/momentum.fgd
> -    EveryTick(integer) : "Every tick" : 0 : "If you want the trigger to update and fire every tick, set this to 1."
Ah, so then in this case, remove the m_bEveryTick member boolean from setspeed as well.

2020-09-13 02:00 UTC, Gocnak commented
Also if possible, please rebase onto latest develop by doing:
```
git fetch -p
git rebase origin/develop
```

Then once everything is confirmed to work,

`git push -f`

2020-09-13 04:33 UTC, notbad69 commented on mp/game/momentum/momentum.fgd
> -    EveryTick(integer) : "Every tick" : 0 : "If you want the trigger to update and fire every tick, set this to 1."
That value is actually used in that entity's Touch() override. I am just not sure of the behavior with that + refiring it on Think(), I could implement the same on this or remove it on setspeed though. Its up to you of course

2020-09-14 15:00 UTC, Gocnak commented on mp/game/momentum/momentum.fgd
> -    EveryTick(integer) : "Every tick" : 0 : "If you want the trigger to update and fire every tick, set this to 1."
Honestly, I would leave changing other ents to a different branch. Let this branch focus only on catapult stuff

2020-09-15 03:50 UTC, notbad69 commented on mp/game/momentum/momentum.fgd
> -    EveryTick(integer) : "Every tick" : 0 : "If you want the trigger to update and fire every tick, set this to 1."
Yeah, ok that makes more sense. Just clearing it up.

2020-09-16 07:39 UTC, Gocnak requested changes

2020-09-16 07:39 UTC, Gocnak commented on mp/game/momentum/momentum.fgd
> -    EveryTick(integer) : "Every tick" : 0 : "If you want the trigger to update and fire every tick, set this to 1."
I would re-instate this in the meantime then.

2020-09-16 07:39 UTC, Gocnak commented on mp/game/momentum/momentum.fgd
> +@SolidClass base(Trigger) = trigger_momentum_catapult : "Catapult the player in a given diretion at a given velocity."
```suggestion
@SolidClass base(MomentumTrigger) = trigger_momentum_catapult : "Catapult the player in a given diretion at a given velocity."

```

2020-09-19 03:05 UTC, Gocnak approved these changes

2020-09-19 03:05 UTC, merged