Stronger sticky shot sound when charged
momentum-mod/game pull request #954
Opened 2020-09-16 06:15 UTC by braem

Cvar controls which point during the charge a strong sticky shot sound should be played.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

2020-09-16 15:49 UTC, Gocnak commented
Remember the docs repo issue for the new cvar

2020-09-16 18:42 UTC, braem commented
Should this be added to the settings panel with the other SJ settings?

2020-09-16 20:37 UTC, Gocnak commented
Yes

2020-09-16 22:24 UTC, braem commented
Added to settings: 
![image](https://user-images.githubusercontent.com/9014762/93398139-dcd02000-f82f-11ea-801a-25c418a7ba35.png)

Changed wording to use "powerful" instead of "strong". It really does feel powerful.

2020-09-18 03:57 UTC, braem commented
Added cvar for toggling sticky firing sound. Also stopped the "chargestop" sound from playing when `mom_sj_sound_charge_enable` is off.

![image](https://user-images.githubusercontent.com/9014762/93553432-ce652f80-f927-11ea-9e3d-375948fef4d9.png)

2020-09-19 03:56 UTC, Gocnak requested changes

2020-09-19 03:56 UTC, Gocnak commented on mp/game/momentum/resource/momentum_english_ref.res
> +        "MOM_Settings_SJ_ShotSoundTheshold_Label" "Powerful Stickybomb Shot Sound Threshold"
Nothing else is CamelCase here
```suggestion
        "MOM_Settings_SJ_ShotSoundTheshold_Label" "Powerful stickybomb shot sound threshold"
```

2020-09-19 09:45 UTC, braem commented
Fixed that up:
![image](https://user-images.githubusercontent.com/9014762/93664237-22543f00-fa22-11ea-8179-d2aa47b1b78e.png)

2020-09-21 15:15 UTC, Gocnak approved these changes

2020-09-21 15:15 UTC, merged